/**
 * Assessment Field Labels, Tooltips, and Options
 * 
 * Centralized constants for all assessment form strings.
 * Migrated from phaseConfig.ts to improve maintainability and follow
 * "Zero Magic Strings" rule from .cursorrules
 */

// Assessment submit button labels (Save for Later / Update Report / Generate Report)
export const ASSESSMENT_SUBMIT_LABELS = {
  SAVE_FOR_LATER: 'Save for Later',
  UPDATE_REPORT: 'Update Report',
  GENERATE_REPORT: 'Generate Report',
  COMPLETE_SECTION_HINT: 'Complete a section to generate report',
} as const;

// Phase Titles and Summaries
export const PHASE_TITLES = {
  P0: 'Basic Client Info',
  P1: 'Lifestyle Factors',
  P2: 'Body Composition',
  P3: 'Metabolic Fitness',
  P4: 'Movement Quality',
  P5: 'Functional Strength',
  P6: 'Goals & Planning',
  P7: 'Results',
} as const;

export const PHASE_SUMMARIES = {
  P0: 'Collect basic client information and health screening.',
  P1: 'Daily habits that impact training and recovery.',
  P2: 'Body composition scan and analysis.',
  P3: 'Resting heart rate and cardio fitness assessment.',
  P4: 'Posture, movement patterns, and mobility screens.',
  P5: 'Basic strength and endurance metrics.',
  P6: 'Set ambitions after we understand your baseline.',
  P7: 'Review results and create reports.',
} as const;

// Gate Hints
export const PHASE_GATE_HINTS: Record<string, string | undefined> = {
  P0: 'Complete before starting assessment.',
  P1: 'Complete lifestyle before health screening.',
  P2: 'Complete before movement assessment.',
  P3: 'Complete first physical assessment - requires resting heart rate.',
  P4: undefined,
  P5: 'Complete movement before strength testing.',
  P6: undefined,
  P7: 'Assessment complete.',
};

// Field Labels by Phase
export const ASSESSMENT_LABELS = {
  P0: {
    fullName: 'Name',
    email: 'Email address',
    phone: 'Phone number',
    dateOfBirth: 'Date of birth',
    gender: 'Gender',
    trainingHistory: 'Training History',
    recentActivity: 'Recent Activity',
    primaryTrainingStyles: 'Training Styles',
    primaryTrainingStyleOther: 'Other Training Style',
    parqQuestionnaire: 'PAR-Q Questionnaire',
  },
  P1: {
    activityLevel: 'Activity Level',
    stepsPerDay: 'Average steps per day',
    sedentaryHours: 'Sedentary hours',
    sleepArchetype: 'Sleep habits',
    sleepQuality: 'Sleep quality', // Legacy
    sleepDuration: 'Sleep Duration', // Legacy
    sleepConsistency: 'Sleep schedule consistency', // Legacy
    stressLevel: 'Stress levels',
    nutritionHabits: 'Nutrition habits',
    hydrationHabits: 'Hydration habits',
    caffeineCupsPerDay: 'Caffeine intake (cups per day)',
    lastCaffeineIntake: 'Time of last caffeine intake',
    alcoholFrequency: 'Alcohol',
    medicationsFlag: 'Regular medications',
    medicationsNotes: 'Medication details',
  },
  P2: {
    heightCm: 'Height (cm)',
    inbodyWeightKg: 'Weight (kg)',
    shouldersCm: 'Shoulders (cm)',
    chestCm: 'Chest (cm)',
    armLeftCm: 'Left Arm (cm)',
    armRightCm: 'Right Arm (cm)',
    waistCm: 'Waist (cm)',
    neckCm: 'Neck (cm)',
    hipsCm: 'Hips (cm)',
    thighLeftCm: 'Left Thigh (cm)',
    thighRightCm: 'Right Thigh (cm)',
    calfLeftCm: 'Left Calf (cm)',
    calfRightCm: 'Right Calf (cm)',
    inbodyScore: 'Body Comp Score',
    skeletalMuscleMassKg: 'Skeletal Muscle Mass (kg)',
    bodyFatMassKg: 'Body Fat Mass (kg)',
    inbodyBodyFatPct: 'Body Fat (%)',
    inbodyBmi: 'BMI',
    totalBodyWaterL: 'Total Body Water (L)',
    waistHipRatio: 'Waist-to-Hip Ratio (WHR)',
    visceralFatLevel: 'Visceral Fat Level',
    segmentalTrunkKg: 'Trunk lean (kg)',
    segmentalArmLeftKg: 'Left arm',
    segmentalArmRightKg: 'Right arm',
    segmentalLegLeftKg: 'Left leg',
    segmentalLegRightKg: 'Right leg',
    bmrKcal: 'BMR (kcal)',
  },
  P3: {
    cardioTestSelected: 'Select test',
    cardioRestingHr: 'Resting Heart Rate (bpm)',
    cardioPeakHr: 'Peak Heart Rate (bpm)',
    cardioPost1MinHr: 'Recovery Heart Rate (bpm)',
  },
  P4: {
    postureInputMode: 'Assessment Method',
    postureHeadOverall: 'Head and neck alignment',
    postureShouldersOverall: 'Shoulder and upper back',
    postureBackOverall: 'Back and spine',
    postureHipsOverall: 'Hips alignment',
    postureKneesOverall: 'Knees alignment',
    ohsShoulderMobility: 'Shoulder mobility',
    ohsTorsoLean: 'Torso lean',
    ohsSquatDepth: 'Squat depth',
    ohsHipShift: 'Hip shift',
    ohsKneeAlignment: 'Knee alignment',
    ohsFeetPosition: 'Foot behaviour',
    ohsHasPain: 'Pain or Discomfort?',
    ohsPainLevel: 'Pain Level (1-10)',
    hingeDepth: 'Depth',
    hingeBackRounding: 'Back rounding',
    hingeHasPain: 'Pain or Discomfort?',
    hingePainLevel: 'Pain Level (1-10)',
    lungeLeftBalance: 'Balance',
    lungeRightBalance: 'Balance',
    lungeLeftKneeAlignment: 'Knee tracking',
    lungeRightKneeAlignment: 'Knee tracking',
    lungeLeftTorso: 'Hip shift',
    lungeRightTorso: 'Hip shift',
    lungeHasPain: 'Pain or Discomfort?',
    lungePainLevel: 'Pain Level (1-10)',
    mobilityHip: 'Hip mobility',
    mobilityShoulder: 'Shoulder mobility',
    mobilityAnkleLeft: 'Ankle mobility (Left)',
    mobilityAnkleRight: 'Ankle mobility (Right)',
  },
  P5: {
    squatsOneMinuteReps: 'Squats in one minute',
    pushupsOneMinuteReps: 'Pushups in one minute',
    plankDurationSeconds: 'Plank duration (seconds)',
    gripTestMethod: 'Select grip test method',
    gripLeftKg: 'Left hand',
    gripRightKg: 'Right hand',
    gripDeadhangSeconds: 'Dead hang time (seconds)',
    gripPlatePinchSeconds: 'Plate pinch time (seconds)',
  },
  P6: {
    clientGoals: 'Primary and secondary goals',
    goalLevelWeightLoss: 'Weight loss target',
    goalLevelMuscle: 'Muscle gain target',
    goalLevelStrength: 'Strength target',
    goalLevelFitness: 'Fitness target',
    goalLevelBodyRecomp: 'Body recomposition target',
  },
} as const;

// Field Tooltips by Phase
export const ASSESSMENT_TOOLTIPS = {
  P0: {
    fullName: 'Enter the client\'s official full name for report generation.',
    email: 'Used for sending the digital assessment report.',
    phone: 'Used for SMS notifications and contact.',
    dateOfBirth: 'Required to calculate age-adjusted health and fitness scores.',
    gender: 'Used for physiological baseline comparisons (SMM, Body Fat).',
    trainingHistory: 'Experience level determines the speed of physiological adaptations (e.g., "Newbie Gains" vs. Diminishing Returns).',
    recentActivity: 'Current readiness determines joint/tendon durability and immediate volume tolerance.',
    primaryTrainingStyles: 'Select all training styles you engage in. Provides context for functional tests.',
    primaryTrainingStyleOther: 'Describe your other training style(s).',
    parqQuestionnaire: 'Instructions:\n1. Answer each question carefully.\n2. Any "YES" answer requires medical clearance before physical testing.',
  },
  P1: {
    activityLevel: 'Instructions:\n1. Consider daily movement outside of the gym (job, chores).\n2. Sedentary = Desk job, minimal walking.\n3. Active = Standing job or 10k+ steps daily.',
    stepsPerDay: 'Typical daily steps over the last 1–2 weeks (watch/phone estimate is fine).',
    sedentaryHours: 'Approximate hours spent sitting or inactive on a typical day.',
    sleepArchetype: 'Select the option that best describes your overall sleep pattern.',
    sleepQuality: 'Coach framing: overall restfulness and continuity (uninterrupted sleep, fewer awakenings, feel rested). Not deep sleep %, just perceived quality.', // Legacy
    sleepDuration: 'Average total hours of sleep per night over the last 1–2 weeks.', // Legacy
    sleepConsistency: 'How consistent are bedtime and wake times across the week.', // Legacy
    stressLevel: 'Perceived day-to-day stress (work, life load). Helps modulate training intensity.',
    nutritionHabits: 'Overall food quality and consistency (protein, whole foods, balanced meals).',
    hydrationHabits: 'Typical daily water/fluid intake and consistency.',
    caffeineCupsPerDay: 'Average number of caffeinated drinks per day (coffee, tea, energy drinks).',
    lastCaffeineIntake: 'Time of your most recent caffeine serving (helps with sleep timing).',
    alcoholFrequency: 'Typical alcohol pattern over the last few months (affects recovery and body composition).',
    medicationsFlag: 'Whether the client takes regular prescription or over-the-counter medications that may affect exercise.',
    medicationsNotes: 'List medications and relevant notes (dose timing, conditions). Optional but recommended when medications are reported.',
  },
  P2: {
    heightCm: 'Required for BMI and body composition calculations.',
    inbodyWeightKg: 'Required for BMI and body composition calculations.',
    shouldersCm: 'Optional: Measure around the widest part of the shoulders. Used for muscle mass estimation when analyzer data is not available.',
    chestCm: 'Optional: Measure around the chest at nipple level. Used for muscle mass estimation when analyzer data is not available.',
    armLeftCm: 'Optional: Measure around the midpoint of the upper arm (bicep). Used for muscle mass estimation when analyzer data is not available.',
    armRightCm: 'Optional: Measure around the midpoint of the upper arm (bicep). Used for muscle mass estimation when analyzer data is not available.',
    waistCm: 'Measure at the narrowest point, or at navel level. Required for body fat calculation (US Navy method) when analyzer data is not available.',
    neckCm: 'Measure just below the larynx (Adam\'s apple). Required for body fat calculation (US Navy method) when analyzer data is not available.',
    hipsCm: 'Measure at the widest part of the hips. Required for women\'s body fat calculation when analyzer data is not available.',
    thighLeftCm: 'Optional: Measure around the midpoint of the thigh. Used for muscle mass estimation when analyzer data is not available.',
    thighRightCm: 'Optional: Measure around the midpoint of the thigh. Used for muscle mass estimation when analyzer data is not available.',
    calfLeftCm: 'Optional: Measure around the widest part of the calf. Used for progress tracking.',
    calfRightCm: 'Optional: Measure around the widest part of the calf. Used for progress tracking.',
    inbodyScore: 'A combined health score from your body composition analyser that increases as you gain muscle and lose body fat.',
    skeletalMuscleMassKg: 'The weight of the muscles you can strengthen and grow. More muscle boosts metabolism and functional strength.',
    bodyFatMassKg: 'The total weight of fat in your body. We use this to track actual fat loss versus just weight changes.',
    inbodyBodyFatPct: 'The percentage of your body weight that is fat. This is a primary indicator of long-term health risk.',
    inbodyBmi: 'A general score based on your height and weight. Useful for broad health category tracking.',
    totalBodyWaterL: 'The amount of fluid in your body. Helps ensure your scan results are consistent and accurate.',
    waistHipRatio: 'A measure of fat distribution. Lower ratios generally indicate lower risk of metabolic health issues.',
    visceralFatLevel: 'The level of fat stored deep around your internal organs. Staying below 10 is ideal for health.',
    segmentalTrunkKg: 'The amount of muscle in your core and torso region.',
    segmentalArmLeftKg: 'Muscle mass in your left arm. Compare with your right side to check for balance.',
    segmentalArmRightKg: 'Muscle mass in your right arm. Compare with your right side to check for balance.',
    segmentalLegLeftKg: 'Muscle mass in your left leg. Compare with your right side to check for balance.',
    segmentalLegRightKg: 'Muscle mass in your right leg. Compare with your left side to check for balance.',
    bmrKcal: 'The calories your body burns at rest. This helps us set your personalised nutrition targets.',
  },
  P3: {
    cardioTestSelected: 'Instructions:\n1. Choose the YMCA Step Test for a portable option.\n2. Choose the Treadmill Test for a more controlled environment.',
    cardioRestingHr: 'Instructions:\n1. Client should sit quietly for 5 minutes.\n2. Measure pulse for 60s or use a heart rate monitor.\n3. Record before starting the test.',
    cardioPeakHr: 'Record the highest heart rate reached just after completing the test (at the 3-minute mark).\n\nStep Test: Record HR immediately after stepping down.\nTreadmill: Record HR right before stopping.',
    cardioPost1MinHr: 'Instructions:\n1. Stop the test at exactly 3:00.\n2. Have client sit down immediately.\n3. Wait exactly 60 seconds.\n4. Record heart rate at the 1-minute mark.\n\nBoth tests use the same recovery measurement.',
  },
  P4: {
    postureInputMode: 'Instructions:\n1. Choose "AI Posture Scan" for automated landmark detection using the camera (e.g. phone or tablet as a companion device).\n2. Choose "Manual" to record observations directly.',
    postureHeadOverall: 'Instructions:\n1. Observe client from the side view.\n2. Note if the ear is positioned directly over the shoulder (Neutral).\n3. If the head sits forward of the shoulder line, mark as Forward Head.',
    postureShouldersOverall: 'Instructions:\n1. View from the side for rounded positions.\n2. View from the back for height symmetry or winged blades.\n3. Note any persistent elevation on one side.',
    postureBackOverall: 'Instructions:\n1. Observe spinal curves from the side view.\n2. Note excessive upper back rounding or lower back arch.\n3. Check for side-to-side lateral curve from the back.',
    postureHipsOverall: 'Instructions:\n1. Place hands on hip bones from the side.\n2. Note if the pelvis tilts forward (Anterior) or backward (Posterior).\n3. Check for height difference between left and right sides.',
    postureKneesOverall: 'Instructions:\n1. View from the front for inward/outward bowing.\n2. Inward cave = Valgus; Outward bow = Varus.\n3. Note any excessive locking back (hyperextension) from the side.',
    ohsShoulderMobility: 'Instructions:\n1. Stand with feet shoulder-width apart.\n2. Raise arms overhead with elbows locked.\n3. Note if arms stay vertical or tilt forward.',
    ohsTorsoLean: 'Instructions:\n1. Squat as deep as comfortable.\n2. Observe from the side view.\n3. Note if the torso stays upright or leans excessively forward.',
    ohsSquatDepth: 'Instructions:\n1. Observe depth relative to parallel.\n2. Full = Hips below knees.\n3. Parallel = Thighs horizontal.',
    ohsHipShift: 'Instructions:\n1. Observe from the back view.\n2. Watch for hips drifting to one side during the squat.',
    ohsKneeAlignment: 'Instructions:\n1. View from the front.\n2. Note if knees cave in (Valgus) or bow out (Varus) during movement.',
    ohsFeetPosition: 'Instructions:\n1. Watch for arches collapsing (Pronation) or feet turning out excessively.',
    ohsHasPain: 'Does the client feel any pain or discomfort during this movement?',
    ohsPainLevel: 'Rate the intensity of the pain reported.',
    hingeDepth: 'Instructions:\n1. Perform a hip hinge (reaching hips back).\n2. Note the range of motion before form breaks or hamstrings limit movement.',
    hingeBackRounding: 'Instructions:\n1. Watch the lumbar spine during the hinge.\n2. Note any rounding (flexion) as the client reaches back.',
    hingeHasPain: 'Does the client feel any pain or discomfort during this movement?',
    hingePainLevel: 'Rate the intensity of the pain reported.',
    lungeLeftBalance: 'Instructions:\n1. Step forward into a lunge.\n2. Note any wobble or loss of stability on the working leg.',
    lungeRightBalance: 'Instructions:\n1. Step forward into a lunge.\n2. Note any wobble or loss of stability on the working leg.',
    lungeLeftKneeAlignment: 'Instructions:\n1. Watch the front knee during the descent.\n2. Note if the knee stays over the foot or caves inward.',
    lungeRightKneeAlignment: 'Instructions:\n1. Watch the front knee during the descent.\n2. Note if the knee stays over the foot or caves inward.',
    lungeLeftTorso: 'Instructions:\n1. Observe from the front or back view.\n2. Note if the hips shift to one side during the lunge.\n3. This indicates asymmetrical strength or stability.',
    lungeRightTorso: 'Instructions:\n1. Observe from the front or back view.\n2. Note if the hips shift to one side during the lunge.\n3. This indicates asymmetrical strength or stability.',
    lungeHasPain: 'Does the client feel any pain or discomfort during this movement?',
    lungePainLevel: 'Rate the intensity of the pain reported.',
    mobilityHip: 'Instructions:\n1. Perform active hip flexion and internal/external rotation tests.\n2. Record range of motion quality.',
    mobilityShoulder: 'Instructions:\n1. Perform reaching tests (Apley scratch test or similar).\n2. Record quality of overhead and behind-back reach.',
    mobilityAnkleLeft: 'Instructions:\n1. Knee-to-wall test on the left ankle.\n2. Note if movement is restricted by tightness or joint block.',
    mobilityAnkleRight: 'Instructions:\n1. Knee-to-wall test on the right ankle.\n2. Note if movement is restricted by tightness or joint block.',
  },
  P5: {
    squatsOneMinuteReps: 'Instructions:\n1. Set timer for 60 seconds.\n2. Count only reps with full range of motion (thighs parallel to floor).\n3. Stop immediately when time expires.',
    pushupsOneMinuteReps: 'Instructions:\n1. Maintain a rigid plank position throughout.\n2. Chest must come within 2 inches of the floor.\n3. Arms must reach full lockout at the top.',
    plankDurationSeconds: 'Instructions:\n1. Hold a forearm plank with a flat back and active core.\n2. Record the total time until form breaks or knees touch.',
    gripTestMethod: 'Choose the test method based on your client\'s needs and available equipment.',
    gripLeftKg: 'Instructions:\n1. Squeeze the dynamometer with maximum effort.\n2. Keep arm at your side, not touching your body.\n3. Record the best of 3 attempts.',
    gripRightKg: 'Instructions:\n1. Squeeze the dynamometer with maximum effort.\n2. Keep arm at your side, not touching your body.\n3. Record the best of 3 attempts.',
    gripDeadhangSeconds: 'Instructions:\n1. Hang from a pull-up bar with full grip.\n2. Record maximum time until grip fails or form breaks.\n3. Bodyweight is used to calculate equivalent grip strength.',
    gripPlatePinchSeconds: 'Instructions:\n1. Pinch grip a standardised weight plate (10kg for females, 15kg for males).\n2. Lift and hold for maximum time.\n3. Record time in seconds until grip fails.',
  },
  P6: {
    clientGoals: 'Select your primary goal first (the one you want to focus on first). Then add any secondary goals. Order determines how we structure your phases: Phase 1 focuses on your primary goal.',
    goalLevelWeightLoss: 'Select your target weight loss. This can be a percentage of your total body weight or a specific amount in kilograms.',
    goalLevelMuscle: 'Select your target muscle gain in kilograms. The recommended option provides a realistic and sustainable rate of muscle growth.',
    goalLevelStrength: 'Select your target strength improvement. Recommended options are based on your training experience and current fitness level.',
    goalLevelFitness: 'Select your target fitness level. Targets are based on VO2 max percentiles and include specific RHR and recovery HR goals.',
    goalLevelBodyRecomp: 'Select your target body composition look. Body recomposition uses a slight calorie deficit to lose fat while building muscle simultaneously. Target body fat percentages are automatically adjusted based on your gender.',
  },
} as const;

// Field Placeholders by Phase
export const ASSESSMENT_PLACEHOLDERS = {
  P0: {
    fullName: 'First and last name',
    email: 'client@email.com',
    phone: '(555) 123-4567',
  },
  P1: {
    stepsPerDay: 'e.g., 6500',
    sedentaryHours: 'e.g., 8',
    caffeineCupsPerDay: 'e.g., 2',
  },
  P2: {
    heightCm: 'e.g., 175',
    inbodyWeightKg: 'e.g., 78.2',
    shouldersCm: 'e.g., 110',
    chestCm: 'e.g., 100',
    armLeftCm: 'e.g., 32',
    armRightCm: 'e.g., 33',
    waistCm: 'e.g., 85',
    neckCm: 'e.g., 38',
    hipsCm: 'e.g., 95',
    thighLeftCm: 'e.g., 58',
    thighRightCm: 'e.g., 59',
    calfLeftCm: 'e.g., 38',
    calfRightCm: 'e.g., 38',
    inbodyScore: 'e.g., 78',
    skeletalMuscleMassKg: 'e.g., 36.4',
    bodyFatMassKg: 'e.g., 21.3',
    inbodyBodyFatPct: 'e.g., 18.5',
    inbodyBmi: 'e.g., 24.8',
    totalBodyWaterL: 'e.g., 41.0',
    waistHipRatio: 'e.g., 0.92',
    visceralFatLevel: 'e.g., 9',
    segmentalTrunkKg: 'e.g., 28.5',
    segmentalArmLeftKg: 'e.g., 3.1',
    segmentalArmRightKg: 'e.g., 3.2',
    segmentalLegLeftKg: 'e.g., 9.1',
    segmentalLegRightKg: 'e.g., 9.7',
    bmrKcal: 'e.g., 1620',
  },
  P5: {
    squatsOneMinuteReps: 'e.g., 40',
    pushupsOneMinuteReps: 'e.g., 25',
    plankDurationSeconds: 'e.g., 60',
    gripLeftKg: 'e.g., 24',
    gripRightKg: 'e.g., 26',
    gripDeadhangSeconds: 'e.g., 45',
    gripPlatePinchSeconds: 'e.g., 30',
  },
  P6: {
    clientGoals: 'Select primary goal first, then any secondary goals',
  },
} as const;

// Option Labels (shared across phases)
export const ASSESSMENT_OPTIONS = {
  gender: [
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
  ],
  trainingHistory: [
    { value: 'beginner', label: 'None / Beginner (< 6 months)' },
    { value: 'intermediate', label: 'Intermediate (6 months – 2 years)' },
    { value: 'advanced', label: 'Advanced (> 2 years consistent training)' },
  ],
  recentActivity: [
    { value: 'currently-training', label: 'Currently Training' },
    { value: 'stopped-3-months', label: 'Stopped < 3 months ago' },
    { value: 'stopped-6-months', label: 'Stopped > 6 months ago' },
  ],
  primaryTrainingStyles: [
    { value: 'bodybuilding', label: 'Bodybuilding / Hypertrophy' },
    { value: 'powerlifting', label: 'Powerlifting / Strength' },
    { value: 'crossfit', label: 'CrossFit / Functional Fitness' },
    { value: 'running', label: 'Running / Endurance' },
    { value: 'yoga-pilates', label: 'Yoga / Pilates' },
    { value: 'hiit', label: 'HIIT / Bootcamps' },
    { value: 'other', label: 'Other' },
  ],
  clientGoals: [
    { value: 'build-muscle', label: 'Build muscle' },
    { value: 'weight-loss', label: 'Weight loss' },
    { value: 'body-recomposition', label: 'Body recomposition' },
    { value: 'build-strength', label: 'Build strength' },
    { value: 'improve-fitness', label: 'Improve fitness' },
    { value: 'general-health', label: 'General health' },
  ],
  goalLevelWeightLoss: [
    { value: '5', label: '5% body weight' },
    { value: '10', label: '10% body weight' },
    { value: '15', label: '15% body weight (recommended)' },
    { value: '5kg', label: '5 kg weight loss' },
    { value: '10kg', label: '10 kg weight loss' },
    { value: '15kg', label: '15 kg weight loss' },
  ],
  goalLevelMuscle: [
    { value: '2', label: '2 kg' },
    { value: '4', label: '4 kg' },
    { value: '6', label: '6 kg (recommended)' },
    { value: '8', label: '8 kg' },
  ],
  goalLevelStrength: [
    { value: 'foundation', label: 'Build a foundation – Focus on technique and consistency' },
    { value: 'modest-10-15', label: 'Improve strength by 10-15% – Modest, sustainable gains' },
    { value: 'solid-20-25', label: 'Improve strength by 20-25% – Solid progress' },
    { value: 'ambitious-30-40', label: 'Improve strength by 30-40% – Ambitious gains' },
    { value: 'aggressive-50', label: 'Improve strength by 50%+ – Aggressive progression' },
    { value: 'maximize', label: 'Maximise strength potential – Elite-level focus' },
  ],
  goalLevelFitness: [
    { value: 'health', label: 'Health Focus (50th percentile)' },
    { value: 'active', label: 'Active (75th percentile) (recommended)' },
    { value: 'athletic', label: 'Athletic (85th percentile)' },
    { value: 'elite', label: 'Elite (95th percentile)' },
  ],
  goalLevelBodyRecomp: [
    { value: 'healthy', label: 'Healthy / Soft' },
    { value: 'fit', label: 'Fit' },
    { value: 'athletic', label: 'Athletic (recommended)' },
    { value: 'shredded', label: 'Shredded' },
  ],
  // P1 Options
  activityLevel: [
    { value: 'sedentary', label: 'Sedentary' },
    { value: 'lightly-active', label: 'Lightly Active' },
    { value: 'moderately-active', label: 'Moderately Active' },
    { value: 'very-active', label: 'Very Active' },
    { value: 'extremely-active', label: 'Extremely Active' },
  ],
  sleepArchetype: [
    { value: 'excellent', label: 'My sleep is consistent – I get 7-9 hours with minimal disruptions' },
    { value: 'good', label: 'I get enough sleep but my schedule or quality varies' },
    { value: 'fair', label: 'I often don\'t get enough sleep or wake frequently' },
    { value: 'poor', label: 'Sleep is a major challenge – irregular schedule and poor quality' },
  ],
  // Legacy sleep options kept for backward compatibility
  sleepQuality: [
    { value: 'poor', label: 'Poor' },
    { value: 'fair', label: 'Fair' },
    { value: 'good', label: 'Good' },
    { value: 'excellent', label: 'Excellent' },
  ],
  sleepDuration: [
    { value: 'less-than-7', label: 'Less than 7 Hours' },
    { value: '7-9', label: '7 to 9 Hours (Ideal)' },
    { value: 'more-than-9', label: 'More than 9 Hours' },
  ],
  sleepConsistency: [
    { value: 'very-inconsistent', label: 'Very inconsistent' },
    { value: 'inconsistent', label: 'Inconsistent' },
    { value: 'consistent', label: 'Consistent' },
    { value: 'very-consistent', label: 'Very consistent' },
  ],
  stressLevel: [
    { value: 'very-low', label: 'I manage stress well and feel balanced most days' },
    { value: 'low', label: 'I experience some stress but cope reasonably' },
    { value: 'moderate', label: 'Stress affects me regularly and impacts my energy' },
    { value: 'high', label: 'I\'m frequently stressed and it significantly affects my life' },
  ],
  nutritionHabits: [
    { value: 'excellent', label: 'I eat mostly whole foods with balanced meals and consistent timing' },
    { value: 'good', label: 'I try to eat healthy but struggle with consistency' },
    { value: 'fair', label: 'My diet varies a lot – sometimes good, sometimes not' },
    { value: 'poor', label: 'I\'m not in control of my eating – mostly takeout/processed' },
  ],
  hydrationHabits: [
    { value: 'excellent', label: 'I drink plenty of water throughout the day consistently' },
    { value: 'good', label: 'I try to stay hydrated but often forget' },
    { value: 'fair', label: 'My water intake varies – sometimes good, sometimes poor' },
    { value: 'poor', label: 'I rarely drink enough water' },
  ],
  alcoholFrequency: [
    { value: 'never', label: 'Rarely or never' },
    { value: 'occasionally', label: 'Occasionally (few times a month)' },
    { value: 'weekly', label: 'About once a week' },
    { value: 'multiple-weekly', label: 'Several times a week' },
    { value: 'frequent', label: 'Most days' },
    { value: 'daily', label: 'Daily' },
  ],
  medicationsFlag: [
    { value: 'no', label: 'No regular medications' },
    { value: 'yes', label: 'Yes — takes medication(s)' },
  ],
  // P3 Options
  cardioTestSelected: [
    { value: 'ymca-step', label: 'YMCA step test' },
    { value: 'treadmill', label: 'Treadmill test' },
  ],
  // P4 Options
  postureInputMode: [
    { value: 'manual', label: 'Manual Observation' },
    { value: 'ai', label: 'AI Posture Scan (camera / companion)' },
  ],
  postureHeadOverall: [
    { value: 'neutral', label: 'Neutral' },
    { value: 'forward-head', label: 'Forward head posture (head juts forward)' },
    { value: 'tilted', label: 'Head tilted to one side' },
    { value: 'chin-tucked', label: 'Chin excessively tucked' },
  ],
  postureShouldersOverall: [
    { value: 'neutral', label: 'Neutral' },
    { value: 'rounded', label: 'Rounded shoulders' },
    { value: 'elevated', label: 'One shoulder elevated' },
    { value: 'winged-scapula', label: 'Scapula winging (shoulder blade sticks out)' },
  ],
  postureBackOverall: [
    { value: 'neutral', label: 'Neutral' },
    { value: 'increased-kyphosis', label: 'Increased upper back curve (rounded upper back)' },
    { value: 'increased-lordosis', label: 'Increased lower back curve (excess lower-back arch)' },
    { value: 'scoliosis', label: 'Lateral spinal curve (side-to-side)' },
    { value: 'flat-back', label: 'Reduced spinal curves (flat back)' },
  ],
  postureHipsOverall: [
    { value: 'neutral', label: 'Neutral' },
    { value: 'anterior-tilt', label: 'Anterior pelvic tilt (pelvis forward)' },
    { value: 'posterior-tilt', label: 'Posterior pelvic tilt (pelvis backward)' },
  ],
  postureKneesOverall: [
    { value: 'neutral', label: 'Neutral' },
    { value: 'valgus-knee', label: 'Knee valgus (knees cave inward)' },
    { value: 'varus-knee', label: 'Knee varus (knees bow outward)' },
  ],
  ohsShoulderMobility: [
    { value: 'full-range', label: 'Full range' },
    { value: 'compensated', label: 'Compensated' },
    { value: 'limited', label: 'Limited' },
  ],
  ohsTorsoLean: [
    { value: 'upright', label: 'Upright' },
    { value: 'moderate-lean', label: 'Moderate lean' },
    { value: 'excessive-lean', label: 'Excessive lean' },
  ],
  ohsSquatDepth: [
    { value: 'full-depth', label: 'Full depth' },
    { value: 'parallel', label: 'Parallel' },
    { value: 'quarter-depth', label: 'Quarter' },
    { value: 'no-depth', label: 'Minimal' },
  ],
  ohsHipShift: [
    { value: 'none', label: 'None' },
    { value: 'left', label: 'Left' },
    { value: 'right', label: 'Right' },
  ],
  ohsKneeAlignment: [
    { value: 'stable', label: 'Stable' },
    { value: 'valgus', label: 'Valgus (knees cave in)' },
    { value: 'varus', label: 'Varus (knees bow out)' },
  ],
  ohsFeetPosition: [
    { value: 'stable', label: 'Stable' },
    { value: 'pronation', label: 'Pronation (rolls inward)' },
    { value: 'supination', label: 'Supination (rolls outward)' },
  ],
  ohsHasPain: [
    { value: 'no', label: 'No pain' },
    { value: 'yes', label: 'Yes - Pain reported' },
  ],
  ohsPainLevel: [
    { value: '1', label: '1 - Very Mild' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4 - Moderate' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7 - Severe' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: '10', label: '10 - Unbearable' },
  ],
  hingeDepth: [
    { value: 'excellent', label: 'Excellent' },
    { value: 'good', label: 'Good' },
    { value: 'fair', label: 'Fair' },
    { value: 'poor', label: 'Poor' },
  ],
  hingeBackRounding: [
    { value: 'none', label: 'None' },
    { value: 'minor', label: 'Minor' },
    { value: 'moderate', label: 'Moderate' },
    { value: 'severe', label: 'Severe' },
  ],
  hingeHasPain: [
    { value: 'no', label: 'No pain' },
    { value: 'yes', label: 'Yes - Pain reported' },
  ],
  hingePainLevel: [
    { value: '1', label: '1 - Very Mild' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4 - Moderate' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7 - Severe' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: '10', label: '10 - Unbearable' },
  ],
  lungeBalance: [
    { value: 'excellent', label: 'Excellent' },
    { value: 'good', label: 'Good' },
    { value: 'fair', label: 'Fair' },
    { value: 'poor', label: 'Poor' },
  ],
  lungeKneeAlignment: [
    { value: 'tracks-straight', label: 'Tracks straight' },
    { value: 'caves-inward', label: 'Caves inward (valgus)' },
    { value: 'bows-outward', label: 'Bows outward (varus)' },
  ],
  lungeHipShift: [
    { value: 'neutral', label: 'No shift (stable)' },
    { value: 'shifts-left', label: 'Shifts to the left' },
    { value: 'shifts-right', label: 'Shifts to the right' },
  ],
  lungeHasPain: [
    { value: 'no', label: 'No pain' },
    { value: 'yes', label: 'Yes - Pain reported' },
  ],
  lungePainLevel: [
    { value: '1', label: '1 - Very Mild' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4 - Moderate' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7 - Severe' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: '10', label: '10 - Unbearable' },
  ],
  mobilityQuality: [
    { value: 'good', label: 'Good' },
    { value: 'fair', label: 'Fair' },
    { value: 'poor', label: 'Poor' },
  ],
  // P5 Options
  gripTestMethod: [
    { value: 'deadhang', label: 'Dead Hang Test' },
    { value: 'pinch', label: 'Plate Pinch Test' },
  ],
} as const;

// Section Titles
export const SECTION_TITLES = {
  P0: {
    'basic-client-info': 'Basic Client Info',
    parq: 'PAR-Q',
  },
  P1: {
    'lifestyle-overview': 'Lifestyle Factors',
  },
  P2: {
    'body-comp': 'Body Composition',
  },
  P3: {
    'fitness-assessment': 'Metabolic Fitness',
  },
  P4: {
    posture: 'Posture',
    'overhead-squat': 'Overhead Squat',
    'hinge-assessment': 'Hinge',
    'lunge-assessment': 'Lunge',
    mobility: 'Mobility',
  },
  P5: {
    'strength-endurance': 'Functional Strength',
  },
  P6: {
    goals: 'Goals',
  },
} as const;

// Dashboard thresholds
/** Number of days without an assessment before a client is considered inactive */
export const CLIENT_INACTIVE_DAYS = 90;
