export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  DASHBOARD_SCHEDULE: '/dashboard/schedule',
  DASHBOARD_CALENDAR: '/dashboard/calendar',
  DASHBOARD_TEAM: '/dashboard/team',
  ASSESSMENT: '/assessment',
  LOGIN: '/login',
  SETTINGS: '/settings',
  ACHIEVEMENTS: '/achievements',
  ORG_DASHBOARD: '/org/dashboard',
  ORG_DASHBOARD_TEAM: '/org/dashboard/team',
  ORG_DASHBOARD_RETENTION: '/org/dashboard/retention',
  ORG_DASHBOARD_BILLING: '/org/dashboard/billing',
  ORG_DASHBOARD_INTEGRATIONS: '/org/dashboard/integrations',
  CLIENT_VIEW: '/client/:id',
  CLIENT_HISTORY: '/client/:id/history',
  CLIENT_SETTINGS: '/client/:id/settings',
  PUBLIC_REPORT: '/r/:token',
  PUBLIC_REPORT_ACHIEVEMENTS: '/r/:token/achievements',
  PUBLIC_REPORT_ROADMAP: '/r/:token/roadmap',
  PUBLIC_REPORT_LIFESTYLE: '/r/:token/lifestyle',
  PUBLIC_REPORT_ERASURE: '/r/:token/erasure',
  PUBLIC_REPORT_PRE_SESSION: '/r/:token/pre-session',
  ASSESSMENT_REPORT: '/coach/assessments/:id',
  ASSESSMENT_REPORT_CLIENT: '/coach/assessments/:id/client',
  ABOUT: '/about',
  CONTACT: '/contact',
  BLOG: '/blog',
  COOKIES: '/cookies',
  DEMO: '/demo',
  COMPARE: '/compare',
  BILLING: '/billing',
  BILLING_SUCCESS: '/billing/success',
  /** Gym trial expired — full-page upgrade (Everfit-style entry to checkout). */
  SUBSCRIBE: '/subscribe',
  ONBOARDING: '/onboarding',
  TRY: '/try',
  CLIENT_ROADMAP: '/coach/clients/:name/roadmap',

  /** Platform admin (separate from org admin) */
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_SETUP: '/admin/setup',
  ADMIN_ORGANIZATIONS: '/admin/organizations',
  ADMIN_ORGANIZATION: (orgId: string) => `/admin/organizations/${orgId}` as const,
} as const;
