export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  ASSESSMENT: '/assessment',
  LOGIN: '/login',
  SETTINGS: '/settings',
  ACHIEVEMENTS: '/achievements',
  ORG_DASHBOARD: '/org/dashboard',
  CLIENT_VIEW: '/client/:id',
  PUBLIC_REPORT: '/r/:token',
  ASSESSMENT_REPORT: '/coach/assessments/:id',
  ASSESSMENT_REPORT_CLIENT: '/coach/assessments/:id/client',
  ABOUT: '/about',
  CONTACT: '/contact',
  BLOG: '/blog',
  COOKIES: '/cookies',
  DEMO: '/demo',
  COMPARE: '/compare',
  BILLING: '/billing',
  ONBOARDING: '/onboarding',
} as const;
