import { Link } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Sparkles, ChevronDown, Menu, Building2 } from 'lucide-react';
import { NotificationBell } from '@/components/notifications/NotificationBell';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

export default function AppShell({
  title,
  subtitle,
  actions,
  children,
  onDemoFill,
  showDemoFill,
  variant = 'default',
  onMenuToggle,
  mode = 'coach',
  // New opt-in branding props for public/unauthenticated views
  publicLogoUrl,
  publicOrgName,
}: {
  title: string;
  subtitle?: string;
  actions?: React.ReactNode;
  children: React.ReactNode;
  onDemoFill?: () => void;
  showDemoFill?: boolean;
  variant?: 'default' | 'full-width';
  onMenuToggle?: () => void;
  mode?: 'coach' | 'public';
  publicLogoUrl?: string | null;
  publicOrgName?: string;
}) {
  const { user, loading, signOut, orgSettings, profile } = useAuth();
  const initials =
    user?.displayName?.split(' ').map((n) => n[0]).join('').toUpperCase() ||
    (user?.email ? user.email[0]?.toUpperCase() : 'C');

  // Use public branding if provided (for unauthenticated routes), otherwise fallback to auth context
  const hasOrgLogo = publicLogoUrl || (orgSettings?.logoUrl && orgSettings.logoUrl.trim() !== '');
  const logoUrl = publicLogoUrl !== undefined ? publicLogoUrl : (hasOrgLogo ? orgSettings?.logoUrl : null);
  const orgName = publicOrgName || orgSettings?.name || 'Your Organization';

  // Public mode: stripped-down layout for client reports
  if (mode === 'public') {
    return (
      <div className="min-h-screen bg-slate-50 text-slate-900">
        {/* Simple Header with JUST the logo (no links) */}
        <header className="bg-white border-b border-slate-200 py-4 px-6 flex justify-center">
          <div className="flex items-center gap-2">
            {logoUrl ? (
              <img
                src={logoUrl}
                alt={orgName}
                className="h-8 w-auto max-w-[150px] object-contain"
              />
            ) : (
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-violet-600 to-indigo-600 flex items-center justify-center text-white font-bold text-sm shadow-md">
                  FF
                </div>
                <span className="font-bold text-slate-900">FitnessFlow</span>
              </div>
            )}
          </div>
        </header>
        
        <main className="max-w-5xl mx-auto py-8 px-4">
          {children}
        </main>

        {/* Simple Footer */}
        <footer className="text-center py-8 text-xs text-slate-400">
          Generated by FitnessFlow
        </footer>
      </div>
    );
  }

  // Coach mode: full layout with navigation
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="border-b border-slate-200 bg-white sticky top-0 z-50 w-full">
        <div className="flex items-center justify-between h-14 sm:h-16 px-3 sm:px-4 md:px-6 lg:px-10">
          {/* Left side: Logo */}
          <div className="flex items-center gap-2 sm:gap-3 md:gap-4 min-w-0">
            {variant === 'full-width' && onMenuToggle && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onMenuToggle}
                className="lg:hidden h-10 w-10 sm:h-9 sm:w-9 text-slate-500"
              >
                <Menu className="h-4 w-4 sm:h-5 sm:w-5" />
              </Button>
            )}
            <Link to="/" className="flex items-center gap-2 sm:gap-3 shrink-0 min-w-0">
              {logoUrl ? (
                // Organization custom logo
                <img
                  src={logoUrl}
                  alt={orgName}
                  className="h-6 w-auto sm:h-8 max-w-[120px] sm:max-w-[150px] object-contain"
                />
              ) : (
                // SaaS default logo (FitnessFlow)
                <div className="flex items-center gap-1.5 sm:gap-2">
                  <div className="w-6 h-6 sm:w-8 sm:h-8 rounded-full bg-gradient-to-tr from-violet-600 to-indigo-600 flex items-center justify-center text-white font-bold text-[10px] sm:text-sm shadow-md">
                    FF
                  </div>
                  <span className="text-base sm:text-lg font-bold tracking-tight text-slate-900 hidden sm:inline">FitnessFlow</span>
                </div>
              )}
              <div className="hidden leading-tight md:block border-l border-slate-200 pl-3 md:pl-4">
                <p className="text-[9px] sm:text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">
                  {orgName}
                </p>
                <p className="text-[10px] sm:text-xs font-semibold text-slate-600">
                  Professional Intake
                </p>
              </div>
            </Link>
          </div>

          {/* Right side: actions/user */}
          <div className="flex items-center gap-1.5 sm:gap-2 md:gap-3 shrink-0">
            {showDemoFill && onDemoFill && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onDemoFill}
                className="h-8 w-8 sm:h-9 sm:w-9 text-slate-400 hover:text-primary hover:bg-brand-light"
                title="Auto-fill demo data"
              >
                <Sparkles className="h-4 w-4 sm:h-5 sm:w-5" />
              </Button>
            )}
            
            <div className="flex items-center gap-1.5 sm:gap-2 md:gap-3">
              {actions ? <div className="flex gap-1 sm:gap-2">{actions}</div> : null}
              {user && <NotificationBell />}
              {!loading && (
                user ? (
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button
                        type="button"
                        className="flex items-center gap-1 sm:gap-2 rounded-full border border-slate-200 bg-white p-0.5 sm:p-1 hover:border-slate-300 transition-colors"
                      >
                        <span 
                          className="flex h-9 w-9 sm:h-8 sm:w-8 items-center justify-center rounded-full text-[11px] sm:text-xs font-bold text-white shadow-sm gradient-bg"
                        >
                          {initials}
                        </span>
                        <ChevronDown className="h-3 w-3 sm:h-4 sm:w-4 text-slate-400 mr-0.5 sm:mr-1" />
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="w-52">
                      <DropdownMenuLabel className="font-normal">
                        <div className="flex flex-col space-y-1">
                          <p className="text-sm font-medium leading-none">{user.displayName || 'Coach Account'}</p>
                          <p className="text-xs leading-none text-slate-500">{user.email}</p>
                        </div>
                      </DropdownMenuLabel>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem asChild>
                        <Link to="/">Dashboard</Link>
                      </DropdownMenuItem>
                      {profile?.role === 'org_admin' && (
                        <DropdownMenuItem asChild>
                          <Link to="/org/dashboard" className="flex items-center gap-2">
                            <Building2 className="h-4 w-4" />
                            Organization
                          </Link>
                        </DropdownMenuItem>
                      )}
                      <DropdownMenuItem asChild>
                        <Link to="/settings">Settings</Link>
                      </DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem
                        className="text-red-600 focus:text-red-600"
                        onClick={() => {
                          void signOut();
                        }}
                      >
                        Sign out
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                ) : (
                  <Button asChild size="sm" variant="outline" className="rounded-full">
                    <Link to="/login">Coach login</Link>
                  </Button>
                )
              )}
            </div>
          </div>
        </div>
      </header>
      
      <main className={`min-h-[calc(100vh-64px)] ${variant === 'default' ? 'mx-auto max-w-7xl px-4 sm:px-6 md:px-8 lg:px-10 py-6 sm:py-8 md:py-10 lg:py-12' : ''}`}>
        {variant === 'default' && (
          <div className="mb-4 sm:mb-6 md:mb-8 space-y-1">
            <h1 className="text-xl sm:text-2xl md:text-3xl font-bold tracking-tight text-slate-900">{title}</h1>
            {subtitle && <p className="text-sm sm:text-base text-slate-500 font-medium">{subtitle}</p>}
          </div>
        )}
        {children}
      </main>
    </div>
  );
}
